Fix typo in seccomp_rule_add.3
seccomp/libseccomp pull request #379
Opened 2022-04-15 15:39 UTC by rusty-snake

Fix typo in seccomp_rule_add.3

2022-04-28 21:28 UTC, drakenclimber requested changes
The change is obviously good to go.

Libseccomp requests that you sign off on the change with your real name.  See here for more details:
https://github.com/seccomp/libseccomp/blob/main/CONTRIBUTING.md#sign-your-work

2022-06-22 21:25 UTC, kolyshkin approved these changes
LGTM(nb)

2022-06-30 12:38 UTC, drakenclimber approved these changes

2022-07-11 01:51 UTC, pcmoore commented
Merged in 85a22fa0ed87bcb2e3023c17ea99295792c2117f, thanks for your patience @rusty-snake!

2022-07-11 01:51 UTC, closed without merging